name: Deploy Production

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            set -e

            cd /root/pdnet/tbep_dev

            git fetch origin
            git reset --hard origin/dev

            docker compose up -d --build nestjs frontend

